---
title: My dynamic report
output: html_fragment
---
 
```{css}
<style>
  body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
  }
  h2 {
    color: purple;
  }
</style>

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
library(tidyverse)
```

```{r}
# import data
logged_data <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7dXYzqjRIlKT8V1lk9EPfupxy_vnE5OZf3mQxCO2hZJ7J1qGscymtOGDXJEboMo6Iadpyv8kGZ6Ve/pub?output=csv")
names(logged_data)
latest_data <- logged_data %>% 
  rename(
    timestamp = Timestamp,
    time_of_completion = `X..Time.of.Completion`,
    time_period = `X...Current.Time.Period`,
    appliances_used = `X..Appliances.Used`,
    total_time_hours = `X....Total.time.of.use.of.all.appliance..hours.`
  )

# execute data
names(latest_data) 
glimpse(latest_data) 
head(latest_data)  
summary(latest_data) 
mean_time <- mean(latest_data$total_time_hours, na.rm = TRUE)
max_time <- max(latest_data$total_time_hours, na.rm = TRUE)
print(paste("Mean of Total Time (hours):", mean_time))
print(paste("Maximum Total Time (hours):", max_time))

# draw a plot
ggplot(latest_data, aes(x = time_period)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Distribution of Appliance Usage by Time Period", x = "Time Period", y = "Frequency") + 
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  geom_text(stat='count', aes(label=..count..), vjust=-0.5)

latest_data$appliance_count <- str_count(latest_data$appliances_used, ",") + 1

ggplot(latest_data, aes(x = appliance_count)) +
  geom_bar(fill = "pink", color = "black") +
  labs(title = "Frequency of Appliances Used", x = "Number of Appliances", y = "Count") + 
  theme(axis.text.x = element_text(hjust = 1)) + 
  geom_text(stat='count', aes(label=..count..), vjust=-0.5) +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal()
```



